### ISSUE TITLE
Ipywidgets not rendered

### ISSUE THREAD

**Issue by French-Kriss** [voila-dashboards/voila-material#12]
Hello, 

There seems to be an issue with some of the _widgets_ from **ipywidget**. 
For instance, the following widgets are not (or wrongly) rendered: 
- Dropdown 
- RadioButtons
- Select

**Comment by martinRenou** [comment]
Thanks for opening an issue. Indeed they do not seem to work.

The `materialiaze` plugin seems to have a CSS rule that hides the select tags by default (until they are initialized):
```
select {
    display: none;
}
```

As a workaround for now, you can try to inject the following CSS to your page:
```
select {
    display: block;
}
```

We could either override this default value, or according to the documentation we can add a `browser-default` class to the element: https://materializecss.com/select.html.

The element would not have a nice materialize look though. We might be able to do better than this.

**Comment by martinRenou** [comment]
You can now try updating to `voila-material 0.3.0` with `pip`. It will soon be available with `conda`.

**Comment by French-Kriss** [comment]
Thank you for the fix. 
Works fine on my side.  👍
