### ISSUE TITLE
loading spinner

### ISSUE THREAD

**Issue by kasrakazemi** [voila-dashboards/voila-material#27]
Hi 
i need custom template to chane loading spinner for my project.
exactly this part:
![Screenshot 2022-06-13 122325](https://user-images.githubusercontent.com/55986800/173306255-1baf61e2-2a1d-4e34-92b2-052a74a3d226.png)

can you guid my which part of your voila-material package must change in order to do that?

**Comment by martinRenou** [comment]
The spinner is implemented in Voila directly https://github.com/voila-dashboards/voila/blob/2b6694191324109c884dc48cc93073977fdacca6/share/jupyter/voila/templates/lab/index.html.j2#L42 If you inherit properly from the base voila template you should get the spinner for free.

**Comment by martinRenou** [comment]
Closing as answered
