### ISSUE TITLE
Spinner doesn't appear when notebook is being executed

### ISSUE THREAD

**Issue by jaladh-singhal** [voila-dashboards/voila-material#9]
Hello team,

When voila executes my notebook using this material theme, I expected that a spinner will appear showing the count of cell being executed, as shown in [this image](https://github.com/voila-dashboards/voila-material/blob/master/material_spinner.png) in your readme. I wanted this because before output of my voila app is displayed by executing the final cell, users have nothing to see - so displaying a spinner/progress bar there, seems intuitive. 

Is there any way to show that spinner in image, in my app? 

Please also let me know if I'm missing something.

**Comment by martinRenou** [comment]
Hello! The spinner should be visible. How many cells do you have in your Notebook?

**Comment by jaladh-singhal** [comment]
@martinRenou 5 cells - only 5th cell displays widgets & plot, other ones show no output, hence I found that spinner is missing while their execution.

**Comment by jaladh-singhal** [comment]
@martinRenou It's really strange, that spinner occurs on 2nd run. I even noticed the same spinner is available in default template also (it has beeen added recently).

But here's another problem, the blank screen still appears after that spinner comes. I've opened a new issue regarding same at [voila repo](https://github.com/voila-dashboards/voila/issues/460). Closing it from here.
